### ISSUE TITLE
DTX1 is decoded incorrectly

### ISSUE THREAD

**Issue by RunDevelopment** [drewcassidy/quicktex#23]
When using the code `dds.read(pathlib.Path(path)).decode().save(target, format="png")` to convert a DTX1 DDS file to PNG, it produces a wrong image. DXT1 supports fully transparent pixels, but those pixels are outputted as black.

**Comment by drewcassidy** [comment]
This is the default behavior, since a lot of BC1 textures are designed around the transparent pixels being decoded as black. The solution is to pass an instance of BC1Decoder with write_alpha set to true, though I guess that isn't very convenient when using the dds.read function. I'll look into a better solution

**Comment by RunDevelopment** [comment]
So the *default behavior* is to ignore transparent pixels and use black instead? May I ask in what context it is useful to ignore the transparency of DDS images and (effectively) apply a black background?

**Comment by drewcassidy** [comment]
BC1 is MOSTLY used for images without transparency. This allows for the transparent pixels to be used for black in order to get better quality, a trick quicktex and many other encoders employ

**Comment by RunDevelopment** [comment]
Is this behavior covered by the format specification?

**Comment by drewcassidy** [comment]
See this is the thing: there kinda isn't a format specification since DXT1 originated as a semi-proprietary format of a now-defunct graphics company. [Microsoft's docs](https://docs.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression#bc1) for BC1 (their name for DXT1 in DirectX 11) just says 

> This algorithm lends itself to data that contains 1-bit alpha also.

Without specifying if the alpha should always be there or not. The OpenGL wiki states 

> A DXT1-compressed image is an RGB image format. As such, the alpha of any color is assumed to be 1

and treats ["DXT1 with alpha"](https://www.khronos.org/opengl/wiki/S3_Texture_Compression#DXT1_with_1-bit_Alpha) as a separate pseudo-format. The Nvidia Texture Tools toolset treats it the same way, and as far as I can tell this was the original intention of the format with the alpha information tacked on after the fact.

In the end there's not much consensus with these formats besides what the GPUs themselves will accept, and its impossible to make it in a way that pleases everyone with all these fuzzy rules in place
